name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Start Docker containers
      run: |
        docker-compose up -d --force-recreate
        sleep 15
        docker ps
        sleep 15

    - name: Run SUT
      run: |
        java -jar artifacts/aqa-shop.jar &
        chmod +x gradlew

    - name: Run tests
      run: |
        ./gradlew test --info -Dselenide.headless=true
